### ISSUE TITLE
Can't install roadiz; database not reachable

### ISSUE THREAD

**Issue by cefuroX** [roadiz/roadiz#364] opened 2020-01-17 10:57 UTC
I try to install roadiz on a local docker using devilbox.
When I try to install roadiz via the intall script (cef-roadiz.loc/install.php) I always get a 500 error with "Your database is not reachable. Did you run install before using Roadiz?"

What I executed:
composer create-project roadiz/standard-edition cef-roadiz
cd cef-roadiz
bin/roadiz themes:generate --symlink --relative Cef
cp .env.dist .env
~ added the DB credentials, but don't know how to add a DB host

So my question is:
How can I add the mysql host and which steps did a miss in order to get this to work? 

Kind regards

**Comment by ambroisemaupate** [comment] 2020-01-17 12:33
Hi @cefuroX 

This is an install issue not a bug. I invite you to create a post on https://ask.roadiz.io/   
I’ll answer you there .

I close this issue in the mean time.

See you on https://ask.roadiz.io/

**Closed by ambroisemaupate** 2020-01-17 12:33 UTC

**Comment by ambroisemaupate** [comment] 2020-01-17 16:52
@cefuroX 

Install is OK for me: 
Here a complete install with Docker
https://www.youtube.com/watch?v=6tMESkNu5Gg

**Comment by cefuroX** [comment] 2020-01-21 11:07
@ambroisemaupate I use another docker instance NOT the roadiz one! I am using devilbox because I have more dependecies than just roadiz. But I will join aks.roadiz.io later today an will post a more detailed question there :)

**Comment by ambroisemaupate** [comment] 2020-01-21 13:10
Issue continues here: https://ask.roadiz.io/d/21-setup-with-diffrent-docker
